spring:
  application:
    name: gateway
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: backend
          uri: lb://backend
          predicates:
            - Path= /backend/**
          filters:
            - StripPrefix=1
server:
  port: 8080
