apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: query-api-account
      containers:
        - name: backend
          image: backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: version
              value: "v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      serviceAccountName: query-api-account
      containers:
        - name: backend
          image: backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: version
              value: "v2"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: backend
